specVersion: 1.0.0
name: nominator-subql
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: Indexing nominations
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/polkadot-dictionary'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 0
    mapping:
      file: ./dist/index.js
      handlers:
      - handler: handleNominate
        kind: substrate/CallHandler
        filter:
          module: staking
          method: nominate
          success: true

